### ISSUE TITLE
Dark mode toggle is missing icon

### ISSUE THREAD

**Issue by arthurmatthew** [arthurmatthew/matthewarthur#2]
Dark mode toggle in top left of page is missing its icon, and appears as a blank circle. This is probably because the Bootstrap Icon pack was uninstalled.

**Comment by AbbeyIT** [comment]
I can see on my part.

Dark Mode:
![image](https://user-images.githubusercontent.com/93916892/193408186-aab1bad9-aaed-4aa4-b564-1e91ce9bc75d.png)

Light Mode:
![image](https://user-images.githubusercontent.com/93916892/193408223-108547bb-ab7d-4eef-9f34-0ec97e6483a7.png)

**Comment by arthurmatthew** [comment]
You're right, thanks!
